### ISSUE TITLE
Build fails due to unresolved "getdtablesize" function

### ISSUE THREAD

**Issue by dbrant** [lubomyr/bochs#1]
Hello!
Thanks for this much-needed port. When I followed your instructions to build it, I got an error due to an unresolved symbol `getdtablesize()` in the file `iodev/network/slirp/misc.cc`.

I was able to simply comment out the block of code that uses `getdtablesize`, and everything built successfully, and runs just fine (since we're not using slirp anyway). But I was wondering if you had come across this issue. Maybe I have something configured wrong, or perhaps we should somehow remove slirp from the build...

**Comment by lubomyr** [comment]
As i see this error appears when using new ndk r11 and latest changes in
pelya's libSDL.

You can try to use previous ndk-r10e -
http://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip
and checkout androidsdl to HEAD 92de300ea58f08054e974d4fb47ea4787a15662a
( cd ~/androidsdl && git checkout 92de300ea58f08054e974d4fb47ea4787a15662a )

We will try to find solution for fix build with new ndk r11.



2016-03-14 5:33 GMT+02:00 Dmitry Brant <notifications@github.com>:

**Comment by lubomyr** [comment]
Pelya fixed this issue

2016-03-15 12:25 GMT+02:00 Lubomyr Lisen <lubomyr31@gmail.com>:
